services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
        - .env
    expose:
        - ${DB_PORT}
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - PGPORT=${DB_PORT}
    volumes:
        - pgdata:/var/lib/postgresql/data/


  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_URL: postgresql+asyncpg://postgres:123@db/gazprome
      REDIS_URL: redis://redis:6379/0
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
    command: poetry run celery -A tasks.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    container_name: worker
    environment:
      REDIS_URL: redis://redis:6379/0
      POSTGRES_URL: postgresql+asyncpg://postgres:123@db/gazprome
      DB_HOST: db

  celery-beat:
    build:
      context: .
    command: celery -A tasks.tasks.celery_app beat --loglevel=info
    volumes:
      - .:/app
    container_name: celery-beat
    environment:
      REDIS_URL: redis://redis:6379/0
      POSTGRES_URL: postgresql+asyncpg://postgres:123@db/gazprome
      DB_HOST: db

volumes:
  pgdata:
