"""empty message

Revision ID: beee9ea68425
Revises: e82bef96450b
Create Date: 2025-04-06 19:28:50.157207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beee9ea68425'
down_revision: Union[str, None] = 'e82bef96450b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'devices_data', 'devices', ['device_id'], ['id'])
    op.alter_column('users', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'device_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'devices_data', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'user_id')
    # ### end Alembic commands ###
